### ISSUE TITLE
(Compatibility list) Add Taiko no Tatsujin: Atsumete Tomodachi Daisakusen as working 

### ISSUE THREAD

**Issue by MysticFlipFlop** [GaryOderNichts/re_nfpii#1]
tried K,K. Slider amiibo, the game recognized it and gave me rewards

**Comment by GaryOderNichts** [comment]
Did you try it with a unregistered/formatted amiibo? Does it open amiibo settings and prompt you to register?
If that's the case it would only be partially supported for now.

**Comment by MysticFlipFlop** [comment]
unregistered
![048ce3ad-05f5-471b-9f60-3232fd86c00e](https://user-images.githubusercontent.com/113185836/189497470-fdc463f0-ca53-4b37-8dda-824415dae2e8.jpg)

**Comment by GaryOderNichts** [comment]
Added it. Thanks for testing!
