### ISSUE TITLE
can't work

### ISSUE THREAD

**Issue by game174master** [GaryOderNichts/re_nfpii#10]
for some reason the application works but when it tells me to select a amiibo that was no amiibo even though I put amiibo file in the re_nfpii folder

**Comment by Mapk68** [comment]
where is the re_nfpii folder loacted?

**Comment by Mapk68** [comment]
This is what should look like: wiiu/re_nfpii and the amiibo shuold be a .bin file

**Comment by game174master** [comment]
you can close the issue I got it
