### ISSUE TITLE
Pokemon Rumble U [0005000010147700]

### ISSUE THREAD

**Issue by giant4ray** [GaryOderNichts/re_nfpii#12]
Game crashes with a black screen when loading any level. The music continues. Console is not frozen and will not allow to leave to the home menu.
Works fine when removing this plugin from the plugin directory. Disabling the plugin does not resolve this issue.

**Comment by GaryOderNichts** [comment]
Looks like Pokemon Rumble U also calls `NFCGetTagInfo` which is currently replaced by the plugin for amiibo detection.
Can you test if it works with the following [nightly build](https://nightly.link/GaryOderNichts/re_nfpii/actions/runs/5219850897/re_nfpii.zip)?

**Comment by giant4ray** [comment]
Thank you for your patience. The issue has indeed been resolved. I tested different scenarios with the plugin disabled and enabled as well and did not run into any issues. Sadly i do not own any of the PKM Rumble U figures, to test if they still work with the plugin in the plugin folder.
