### ISSUE TITLE
New Feature - Organizing Amiibos _ Support SubFolders

### ISSUE THREAD

**Issue by filipe-maia** [GaryOderNichts/re_nfpii#14]
This is a new feature request.
There are a lot of amiibos, and the speed of the scroll list on the Aroma Plugin Settings is very slow.
If possible, please add subfolders support inside '/wiiu/re_nfpii', that way the users can organize amiibos inside folders with the names of the games and/or inside folders with the names of the series of the amiibos.
Thanks.

**Comment by GaryOderNichts** [comment]
This is already a feature since [version 0.2.0](https://github.com/GaryOderNichts/re_nfpii/releases/tag/v0.2.0).
