### ISSUE TITLE
Disney Infinity

### ISSUE THREAD

**Issue by WalterLeal** [GaryOderNichts/re_nfpii#17]
Disney Infinity remains stationary on the "Missing Disney Infinity Base" screen.

Add support for this game please.

**Comment by GaryOderNichts** [comment]
Is this a re_nfpii issue? I don't see how re_nfpii would interfere with Disney Infinity.
This just seems like you're missing the "Disney Infinity Base".

**Comment by Masamune3210** [comment]
Infinity figures aren't amiibos.

**Comment by GaryOderNichts** [comment]
re_nfpii only emulates amiibos.
Like the comment above mentioned, Infinity figures are not amiibos and won't be supported by re_nfpii.

**Comment by WalterLeal** [comment]
Ok. Thanks
