### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by memohomebrew** [GaryOderNichts/re_nfpii#19]
Help!The re_nfpii on The plugin menu is not there Can i have the file please?The file is on Sd/wiiu/environments/aroma/plugins/config

**Comment by memohomebrew** [comment]
Is a JSON file

**Comment by GaryOderNichts** [comment]
That file will be auto-generated, there's no need to manually place it there.
If re_nfpii doesn't show up in the plugin menu, you didn't place the files correctly on the SD Card.
