### ISSUE TITLE
(Compatibility list) Add Star Fox Guard as working

### ISSUE THREAD

**Issue by Zyliqx** [GaryOderNichts/re_nfpii#3]
I tried an unregistered Fox and Falco Amiibo. It got both reconized in game and prompt me to register in Amiibo settings
![Screenshot 2022-09-29 22-49-42](https://user-images.githubusercontent.com/100963654/193139433-4655b066-916e-4358-b6aa-2e4d54e45652.png)

**Comment by GaryOderNichts** [comment]
Added, thanks for testing.
