### ISSUE TITLE
(Compatibility list) Add Mario & Sonic at the Rio 2016 Olympic Games as working

### ISSUE THREAD

**Issue by Zyliqx** [GaryOderNichts/re_nfpii#4]
Unregistered Mario Amiibo got reconized in game and promt me to register in Amiibo settings.

https://user-images.githubusercontent.com/100963654/195700791-3dae1721-8d77-4ee7-8f54-29184d0916d4.mp4

**Comment by GaryOderNichts** [comment]
Thanks for testing, added it to the list. Looks like all games have been confirmed working now!
