### ISSUE TITLE
Amiibo emulation setting resets when scanning amiibo or booting up settings

### ISSUE THREAD

**Issue by DolphinCube** [GaryOderNichts/re_nfpii#5]
Hello! So I have a problem where If I try to scan my amiibo or go to the system settings. The option for "enable amiibo emulation" resets. And also de-selects my amiibo as well. I dont know if its the amiibo bin file issue but I really hope this can be fixed soon. Because I cant do anything and it doesnt show that an amiibo is scanned at all when I go to the scanning screen. I mostly want to do this for shovel knight: treasure trove. Which could be incompatable.

**Comment by GaryOderNichts** [comment]
Make sure you're using a raw dump which hasn't been decrypted.
The option resetting would mean that the module failed to read the amiibo, and disabled emulation again.

**Comment by DolphinCube** [comment]
ah I see. TY for letting me know
