### ISSUE TITLE
Subfolder support & Custom remove after timer

### ISSUE THREAD

**Issue by NedcloarBR** [GaryOderNichts/re_nfpii#8]
# SubFolders
Add support for the plugin to recognize and organize amiibo present in subfolders (wiiu/re_nfpii/SubFolder/amiibo_file.bin)
So when the user emulates the amiibos, he can organize them in his own way and the amiibo selection menu understands and shows the subfolders with the amiibos

## Why add support?
Imagine that the user has a dump of more than 100 amiibos and goes to play a game that has amiibo support but only for specific ones and having to spend a while clicking down until she finds the desired amiibo with the subfolders she can leave the amiibos of that game in a specific folder and find the amiibo you're looking for faster!

# Custom remove after timer
The Mario Party 10 game in Amiibo Party mode to launch the dice blocks is necessary to place the amiibo on the sensor and release it to actually launch the dice block but there is the Slow Dice Block that increases the number that will be launched every 1s going from 1 to 6 and currently the Plugin has a maximum time of 4.5s making it impossible for the user to enjoy the game to the fullest

**Comment by GaryOderNichts** [comment]
Subfolder support has been added in version 0.2.0 and the remove after time has been increased to 10 seconds.
